[package]
name = "wring-twistree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
num-prime = "0.4.3"
num-traits = "0.2.16"
num-integer = "0.1.44"
